### ISSUE TITLE
Migrate to btcd/btcutils submodule

### ISSUE THREAD

**Issue by 3nprob** [btcsuite/btcwallet#787]
As per https://github.com/btcsuite/btcd/pull/1785, `btcutil` needs to migrate as well in order to afford upgrading the `btcd` dependency. Attempting to use current `btcd@master`: 

```
$ GO111MODULE=on go install -v . ./cmd/...
github.com/btcsuite/btcwallet/internal/legacy/keystore
github.com/btcsuite/btcwallet/wallet/txrules
github.com/lightninglabs/neutrino
# github.com/btcsuite/btcwallet/wallet/txrules
wallet/txrules/rules.go:30:23: cannot use relayFeePerKb (type "github.com/btcsuite/btcutil".Amount) as type "github.com/btcsuite/btcd/btcutil".Amount in argument to mempool.IsDust
# github.com/btcsuite/btcwallet/internal/legacy/keystore
internal/legacy/keystore/keystore.go:2795:3: cannot use addresses (type []"github.com/btcsuite/btcd/btcutil".Address) as type []"github.com/btcsuite/btcutil".Address in field value
internal/legacy/keystore/keystore.go:2877:15: cannot use addresses (type []"github.com/btcsuite/btcd/btcutil".Address) as type []"github.com/btcsuite/btcutil".Address in assignment
# github.com/lightninglabs/neutrino
../../../../pkg/mod/github.com/lightninglabs/neutrino@v0.12.1/blockmanager.go:2718:35: cannot use stubBlock (type *"github.com/btcsuite/btcutil".Block) as type *"github.com/btcsuite/btcd/btcutil".Block in argument to blockchain.CheckProofOfWork
../../../../pkg/mod/github.com/lightninglabs/neutrino@v0.12.1/query.go:988:42: cannot use block (type *"github.com/btcsuite/btcutil".Block) as type *"github.com/btcsuite/btcd/btcutil".Block in argument to blockchain.CheckBlockSanity
../../../../pkg/mod/github.com/lightninglabs/neutrino@v0.12.1/rescan.go:931:53: cannot use relevantTxs (type []*"github.com/btcsuite/btcutil".Tx) as type []*"github.com/btcsuite/btcd/btcutil".Tx in argument to ro.ntfn.OnFilteredBlockConnected
../../../../pkg/mod/github.com/lightninglabs/neutrino@v0.12.1/rescan.go:988:26: cannot use tx (type *"github.com/btcsuite/btcutil".Tx) as type *"github.com/btcsuite/btcd/btcutil".Tx in argument to ro.ntfn.OnRedeemingTx
../../../../pkg/mod/github.com/lightninglabs/neutrino@v0.12.1/rescan.go:1004:21: cannot use tx (type *"github.com/btcsuite/btcutil".Tx) as type *"github.com/btcsuite/btcd/btcutil".Tx in argument to ro.ntfn.OnRecvTx
../../../../pkg/mod/github.com/lightninglabs/neutrino@v0.12.1/rescan.go:1048:44: cannot use relevantTxs (type []*"github.com/btcsuite/btcutil".Tx) as type []*"github.com/btcsuite/btcd/btcutil".Tx in argument to ro.ntfn.OnFilteredBlockConnected
```

**Comment by chappjc** [comment]
Related: https://github.com/btcsuite/btcwallet/pull/782
With the last tagged release, you cannot just go get or even add a require for btcwallet because it currently relies on replaces.

**Comment by chappjc** [comment]
Ahhh, dang I did not even see that btcutil was moved into the btcd repo as a submodule in https://github.com/btcsuite/btcd/pull/1785.  About a month ago now.  I'm just going to close the PR I linked, but note that you can get wallet to build if you set your requires to specific revisions in that way.

**Comment by 3nprob** [comment]
@chappjc Ah , I looked at your PR now - I was actually just about to do a similar one here, to address this issue. Would you say that what you addressed in your PR and 825e09bbcf69d4b230f1eb90f5e8b347380cba06 still is relevant to put on top of a `btcd` dependency upgrade here?

**Comment by chappjc** [comment]
The wtxmgr thing is still an issue, especially _for a tagged release_, and all the replaces were just hiding the issues from devs who either work directly out of a git workspace or had their own requires patching it up.  Tagged releases should really have replaces removed.  It would still be nice if 0.13 were properly re-released with a 0.13.1 patch, but with these btcutil changes at hand now, it's probably a moot point now.

I say you should go ahead and fix things up with btcutil.  If the maintainers are interested in a usable 0.13.x with the previous btcutil module, I'm happy to update my PR.

I'm curious if the intent is to bump to 0.14 or just patch 0.13.

**Comment by Roasbeef** [comment]
> With these big btcutil changes, I'm curious if the intent is to bump to 0.14

We'll likely just do a big ump everywhere.

**Comment by Roasbeef** [comment]
Has been done in master.
